#!/usr/bin/env python3
"""Render docs/19-pyfa-feature-inventory.yaml into the tables of docs/19-pyfa-feature-inventory.md
(between the GENERATED markers) and into docs/19-pyfa-feature-inventory.csv."""
import csv, collections, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
Y = ROOT / "docs/19-pyfa-feature-inventory.yaml"
MD = ROOT / "docs/19-pyfa-feature-inventory.md"
CSV = ROOT / "docs/19-pyfa-feature-inventory.csv"
COLS = ["f", "mcp", "web", "formats"]
LABELS = ["F engine/CLI/WASM (eve-dogma)", "eve-fit-mcp", "eve-fit-web", "eve-fit-formats (FMT-* only)"]
HEADS = ["F", "MCP", "WEB", "FORMATS"]
AREAS = [("ENG-CORE", "Engine core"), ("ENG-MOD", "Modules"), ("ENG-SHIP", "Ships, modes, subsystems, structures"),
         ("ENG-DRN", "Drones"), ("ENG-FTR", "Fighters"), ("ENG-IMP", "Implants and boosters"),
         ("ENG-CAP", "Capacitor"), ("ENG-DEF", "Defense / tank"), ("ENG-OFF", "Offense / mining"),
         ("ENG-NAV", "Navigation"), ("ENG-TGT", "Targeting / sensors / misc"), ("ENG-PROJ", "Projection / remote effects"),
         ("ENG-FLT", "Fleet / command"), ("ENG-ENV", "Environment"), ("ENG-VAL", "Validation / restrictions"), ("ENG-MISC", "Other engine items"),
         ("ENG-BATCH", "Batch compute (extra)"), ("ENG-PRICE", "Engine prices (extra)"),
         ("GRF", "Graphs"), ("CHR", "Characters and skills"), ("PRC", "Prices"), ("FMT", "Import / export"),
         ("ESI", "ESI / SSO"), ("DB", "Persistence / fit library"), ("PRF", "Damage patterns / target profiles"),
         ("MKT", "Market / item info"), ("UI", "GUI panes, columns, menus, preferences"), ("SVC", "Services / misc")]
SYM = {"have": "✅ have", "partial": "🟡 partial", "missing": "❌ missing", "n/a": "– n/a"}


def cell(i, c):
    """A column an item does not carry (formats outside FMT-*) renders blank."""
    return f"{SYM[i[c]]}: {esc(i.get(c + '_evidence', ''))}" if c in i else ""


def area(i):
    return next(p for p, _ in sorted(AREAS, key=lambda a: -len(a[0])) if i["id"].startswith(p + "-"))


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def main():
    doc = yaml.safe_load(Y.read_text())
    allitems = doc["items"]
    items = [i for i in allitems if not i.get("extra")]   # parity items (Pyfa); extras are counted separately
    extras = [i for i in allitems if i.get("extra")]
    cnt = {c: collections.Counter(i[c] for i in items if c in i) for c in COLS}
    out = ["<!-- GENERATED by tools/render_inventory.py from the YAML; do not edit by hand -->", "",
           f"## Counts ({len(items)} Pyfa parity items; {len(extras)} extra beyond Pyfa, not counted here)", "",
           "| column | have | partial | missing | n/a |", "|---|---|---|---|---|"]
    for c, lab in zip(COLS, LABELS):
        out.append(f"| {lab} | {cnt[c]['have']} | {cnt[c]['partial']} | {cnt[c]['missing']} | {cnt[c]['n/a']} |")
    out += ["", "Per area (have/partial/missing, n/a not counted):", "", "| area | items | " + " | ".join(HEADS) + " |", "|---|---|" + "---|" * len(COLS)]
    by = collections.defaultdict(list)
    for i in items:
        by[area(i)].append(i)
    for p, name in AREAS:
        g = by.get(p, [])
        if not g:
            continue
        f = lambda c: "/".join(str(sum(1 for i in g if i.get(c) == s)) for s in ("have", "partial", "missing")) if any(c in i for i in g) else "-"
        out.append(f"| {p} {name} | {len(g)} | " + " | ".join(f(c) for c in COLS) + " |")
    if extras:
        ecnt = {c: collections.Counter(i[c] for i in extras if c in i) for c in COLS}
        out += ["", f"Extras beyond Pyfa ({len(extras)} items, `extra: true`; see the header rule):", "",
                "| column | have | partial | missing | n/a |", "|---|---|---|---|---|"]
        for c, lab in zip(COLS, LABELS):
            if ecnt[c]:
                out.append(f"| {lab} | {ecnt[c]['have']} | {ecnt[c]['partial']} | {ecnt[c]['missing']} | {ecnt[c]['n/a']} |")
    out += ["", "## Items", ""]
    for p, name in AREAS:
        g = by.get(p, [])
        if not g:
            continue
        cs = [c for c in COLS if any(c in i for i in g)]
        out += [f"### {p}: {name}", "", "| id | feature | Pyfa source | " + " | ".join(HEADS[COLS.index(c)] for c in cs) + " |",
                "|---|---|---|" + "---|" * len(cs)]
        for i in g:
            own = f" *Owner: {esc(i['owner'])}.*" if i.get("owner") else ""
            out.append(f"| {i['id']} | **{esc(i['name'])}**: {esc(i['description'])}{own} | `{esc(i['pyfa_src'])}` | "
                       + " | ".join(cell(i, c) for c in cs) + " |")
        out.append("")
    if extras:
        cs = [c for c in COLS if any(c in i for i in extras)]
        out += ["## Extras beyond Pyfa", "", "Not part of the parity totals above (`extra: true`).", "",
                "| id | feature | Pyfa source | " + " | ".join(HEADS[COLS.index(c)] for c in cs) + " |", "|---|---|---|" + "---|" * len(cs)]
        for i in extras:
            out.append(f"| {i['id']} | **{esc(i['name'])}**: {esc(i['description'])} | `{esc(i['pyfa_src'])}` | " + " | ".join(cell(i, c) for c in cs) + " |")
        out.append("")
    md = MD.read_text()
    a, b = "<!-- BEGIN GENERATED -->", "<!-- END GENERATED -->"
    head, rest = md.split(a, 1)
    tail = rest.split(b, 1)[1]
    MD.write_text(head + a + "\n" + "\n".join(out) + "\n" + b + tail)
    with CSV.open("w", newline="") as fh:
        w = csv.writer(fh)
        keys = ["id", "area", "extra", "name", "description", "pyfa_src"] + [k for c in COLS for k in (c, c + "_evidence")] + ["owner"]
        w.writerow(keys)
        for i in allitems:
            w.writerow([i["id"], area(i), "yes" if i.get("extra") else ""] + [i.get(k, "") for k in keys[3:]])  # formats columns blank outside FMT-*
    print({c: dict(cnt[c]) for c in COLS}, "extras:", len(extras))


if __name__ == "__main__":
    main()
